# This is a basic workflow that is manually triggered
# This is a basic workflow that is manually triggered

name: build and push image workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      TagVersion:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version of Image tag to build'
        # Default value if no value is explicitly provided
        default: '1.0.0-27092023'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  downloadKnativeFuncCLI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
       
    # Steps represent a sequenc
    # Runs a single command using the runners shell
    - name: dowload Knative Function CLI
      run: | 
       curl -LO https://github.com/knative/func/releases/download/knative-v1.10.0/func_linux_amd64
       chmod a+x func_linux_amd64
       mv func_linux_amd64 knfunc
       ls -lrt
       cp knfunc ${HOME}/knfunc
       ls -lrt ${HOME}
    
    - name: checkKnFunc
      run: /home/runner/knfunc version

    - name: docker login
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: buildAndPushImage
      run: |
       cd /home/runner/work/InvoiceMgrKnative/InvoiceMgrKnative
       /home/runner/knfunc build --registry docker.io/x00159358 --image docker.io/x00159358/invoicemgrimg:${{ inputs.TagVersion }} --push --verbose
